/* ==========================================================================
   PRODUCTS CATALOG DATABASE (AJIO & SHEIN INSPIRED CURATED COLLECTION)
   No external images — uses CSS gradient placeholder colors via `color` field
   ========================================================================== */

/*
  Each product has a `color` array (CSS gradient stops) used to render a
  pure-CSS product card image placeholder, so zero network requests are made
  for images.
*/

const PRODUCTS = [
  {
    id: "p1",
    title: "Oversized Cyberpunk Graphic Hoodie",
    brand: "SHEIN X STREET",
    category: "Streetwear",
    price: 1499,
    originalPrice: 3499,
    discount: 57,
    rating: 4.8,
    reviewCount: 342,
    quantity: 25,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["#12141d", "#7928ca", "#ff0055"],
    colorNames: ["Obsidian Black", "Cyber Purple", "Neon Pink"],
    // Gradient used as card visual placeholder
    gradient: "linear-gradient(135deg, #12141d 0%, #7928ca 50%, #ff0055 100%)",
    image: "images/hoodie_cyberpunk.jpg",
    emoji: "👕",
    isFlashDeal: true,
    isTrending: true,
    description: "Ultra-heavyweight 420 GSM french terry cotton hoodie featuring high-density puff graphic prints, relaxed drop shoulders, and double-layered drawstring hood.",
    inStock: true
  },
  {
    id: "p2",
    title: "Y2K Metallic Holographic Cargo Pants",
    brand: "AJIO LUXE",
    category: "Streetwear",
    price: 2199,
    originalPrice: 4999,
    discount: 56,
    rating: 4.9,
    reviewCount: 215,
    quantity: 18,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#00dfd8", "#c0c0c0", "#12141d"],
    colorNames: ["Cyan Spark", "Liquid Silver", "Midnight"],
    gradient: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #00dfd8 100%)",
    image: "images/cargo_holographic.jpg",
    emoji: "👖",
    isFlashDeal: true,
    isTrending: true,
    description: "High-shine metallic technical nylon fabric with utility deep pockets, adjustable ankle toggles, and dynamic reflective accents for futuristic style.",
    inStock: true
  },
  {
    id: "p3",
    title: "Royal Velvet Embroidered Anarkali Set",
    brand: "INDIE ETHNIC",
    category: "Ethnic",
    price: 3899,
    originalPrice: 7999,
    discount: 51,
    rating: 4.9,
    reviewCount: 489,
    quantity: 12,
    sizes: ["S", "M", "L", "XL"],
    colors: ["#7928ca", "#8b0000", "#006400"],
    colorNames: ["Imperial Purple", "Deep Maroon", "Emerald Green"],
    gradient: "linear-gradient(135deg, #4a0e6b 0%, #7928ca 40%, #c471ed 100%)",
    image: "images/anarkali_velvet.jpg",
    emoji: "👗",
    isFlashDeal: false,
    isTrending: true,
    description: "Handcrafted intricate zari sequin work on plush velvet bodice, matched with tissue organza dupatta and flared pants for festive glamor.",
    inStock: true
  },
  {
    id: "p4",
    title: "Chunky Retro Futuristic Platform Sneakers",
    brand: "SHEIN ICON",
    category: "Footwear",
    price: 2799,
    originalPrice: 5999,
    discount: 53,
    rating: 4.7,
    reviewCount: 184,
    quantity: 20,
    sizes: ["UK 6", "UK 7", "UK 8", "UK 9"],
    colors: ["#ffffff", "#ff0055", "#12141d"],
    colorNames: ["Chalk White", "Neon Blush", "Shadow Black"],
    gradient: "linear-gradient(135deg, #f8f9fa 0%, #dee2e6 50%, #adb5bd 100%)",
    image: "images/sneakers_platform.jpg",
    emoji: "👟",
    isFlashDeal: true,
    isTrending: true,
    description: "Lightweight cloud-sole EVA cushioning platform with layered breathable mesh and synthetic leather paneling.",
    inStock: true
  },
  {
    id: "p5",
    title: "Tailored Double-Breasted Power Blazer",
    brand: "AJIO MAN",
    category: "Western",
    price: 3299,
    originalPrice: 6599,
    discount: 50,
    rating: 4.6,
    reviewCount: 128,
    quantity: 15,
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["#12141d", "#36454f", "#800020"],
    colorNames: ["Jet Black", "Charcoal", "Burgundy"],
    gradient: "linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)",
    image: "images/blazer_power.jpg",
    emoji: "🧥",
    isFlashDeal: false,
    isTrending: false,
    description: "Sharp structural shoulder pads, horn-textured buttons, and satin inner lining engineered for sleek boardroom-to-evening transitions.",
    inStock: true
  },
  {
    id: "p6",
    title: "Cropped Ribbed Corset Top & Cardigan",
    brand: "SHEIN CHIC",
    category: "Western",
    price: 899,
    originalPrice: 1999,
    discount: 55,
    rating: 4.5,
    reviewCount: 620,
    quantity: 30,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#ff0055", "#fffdd0", "#808080"],
    colorNames: ["Barbie Pink", "Creamy Vanilla", "Heather Grey"],
    gradient: "linear-gradient(135deg, #ff0055 0%, #ff758c 50%, #ffb3c1 100%)",
    image: "images/corset_cardigan.jpg",
    emoji: "👚",
    isFlashDeal: true,
    isTrending: true,
    description: "2-in-1 combo feature with figure-sculpting ribbed knit corset top and matching sheer micro cardigan.",
    inStock: true
  },
  {
    id: "p7",
    title: "Minimalist Leather Crossbody Saddle Bag",
    brand: "LUXE COUTURE",
    category: "Bags",
    price: 1899,
    originalPrice: 4299,
    discount: 56,
    rating: 4.8,
    reviewCount: 290,
    quantity: 14,
    sizes: ["One Size"],
    colors: ["#8b4513", "#12141d", "#f5f5dc"],
    colorNames: ["Cognac Tan", "Classic Black", "Ecru Beige"],
    gradient: "linear-gradient(135deg, #5c3317 0%, #8b4513 50%, #c8a882 100%)",
    image: "images/bag_saddle.jpg",
    emoji: "👜",
    isFlashDeal: false,
    isTrending: true,
    description: "Supple vegan leather finish with gold hardware, detachable chain strap, and multiple internal card slots.",
    inStock: true
  },
  {
    id: "p8",
    title: "Chunky Gold Plated Chain Necklace",
    brand: "SHEIN JEWELS",
    category: "Accessories",
    price: 499,
    originalPrice: 1299,
    discount: 61,
    rating: 4.7,
    reviewCount: 740,
    quantity: 50,
    sizes: ["One Size"],
    colors: ["#ffd700", "#c0c0c0"],
    colorNames: ["18K Gold Finish", "Silver Chrome"],
    gradient: "linear-gradient(135deg, #7b6012 0%, #c8a600 50%, #ffd700 100%)",
    image: "images/necklace_gold_chain.jpg",
    emoji: "📿",
    isFlashDeal: true,
    isTrending: false,
    description: "Tarnish-free stainless steel core plated in rich 18K yellow gold, statement toggle lock closure.",
    inStock: true
  },
  {
    id: "p9",
    title: "Vintage Washed Denim Trucker Jacket",
    brand: "AJIO DENIM",
    category: "Streetwear",
    price: 2499,
    originalPrice: 4999,
    discount: 50,
    rating: 4.8,
    reviewCount: 310,
    quantity: 16,
    sizes: ["S", "M", "L", "XL"],
    colors: ["#4682b4", "#12141d"],
    colorNames: ["Vintage Wash Blue", "Raw Indigo Black"],
    gradient: "linear-gradient(135deg, #1a3a5c 0%, #2c6fad 50%, #4682b4 100%)",
    image: "images/jacket_denim_trucker.jpg",
    emoji: "🧥",
    isFlashDeal: false,
    isTrending: true,
    description: "Heavy 14oz rigid cotton denim with distressed seam detailing, buttoned flap pockets, and adjustable waist tabs.",
    inStock: true
  },
  {
    id: "p10",
    title: "Silk Satin Backless Evening Slip Dress",
    brand: "SHEIN GLAM",
    category: "Western",
    price: 1999,
    originalPrice: 4499,
    discount: 55,
    rating: 4.9,
    reviewCount: 512,
    quantity: 22,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#ff0055", "#12141d", "#00dfd8"],
    colorNames: ["Crimson Red", "Midnight", "Emerald Cyan"],
    gradient: "linear-gradient(135deg, #8b0030 0%, #ff0055 50%, #ff5e85 100%)",
    image: "images/dress_slip_satin.jpg",
    emoji: "👘",
    isFlashDeal: true,
    isTrending: true,
    description: "Liquid-touch satin weave with cowl neckline, delicate criss-cross strappy back, and dramatic side slit.",
    inStock: true
  },
  {
    id: "p11",
    title: "Geometric Polarized Matrix Sunglasses",
    brand: "AJIO ACCESS",
    category: "Accessories",
    price: 799,
    originalPrice: 1999,
    discount: 60,
    rating: 4.6,
    reviewCount: 198,
    quantity: 35,
    sizes: ["One Size"],
    colors: ["#12141d", "#00dfd8"],
    colorNames: ["Full Black", "Cyber Mirror"],
    gradient: "linear-gradient(135deg, #090a0f 0%, #1a1a2e 50%, #16213e 100%)",
    emoji: "🕶️",
    isFlashDeal: false,
    isTrending: false,
    description: "UV400 protective polarized lenses housed in ultra-lightweight rimless acetate frame.",
    inStock: true
  },
  {
    id: "p12",
    title: "Hand-Block Printed Cotton Kurta Set",
    brand: "INDIE ETHNIC",
    category: "Ethnic",
    price: 1699,
    originalPrice: 3599,
    discount: 52,
    rating: 4.7,
    reviewCount: 367,
    quantity: 20,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["#008080", "#ff7f50"],
    colorNames: ["Indigo Teal", "Rust Amber"],
    gradient: "linear-gradient(135deg, #003d3d 0%, #008080 50%, #00b3b3 100%)",
    image: "images/kurta_block.jpg",
    emoji: "🩱",
    isFlashDeal: false,
    isTrending: true,
    description: "Pure breathable 100% cotton printed with traditional artisan wooden blocks, includes palazzo pants and matching dupatta.",
    inStock: true
  },
  {
    id: "p13",
    title: "Classic Oxford Button-Down Shirt",
    brand: "IKON ESSENTIALS",
    category: "Shirts & Pants",
    price: 699,
    originalPrice: 1299,
    discount: 46,
    rating: 4.6,
    reviewCount: 183,
    quantity: 40,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["#ffffff", "#87ceeb", "#f5f5dc"],
    colorNames: ["Crisp White", "Sky Blue", "Beige"],
    gradient: "linear-gradient(135deg, #e0eafc 0%, #cfdef3 50%, #a8c0e8 100%)",
    image: "images/shirt_oxford.jpg",
    emoji: "👔",
    isFlashDeal: true,
    isTrending: true,
    description: "Premium 100% cotton Oxford weave fabric with a clean button-down collar, chest patch pocket, and a relaxed regular fit. Perfect for office, casual outings, or smart-casual events.",
    inStock: true
  },
  {
    id: "p14",
    title: "Slim Fit Formal Trousers",
    brand: "IKON ESSENTIALS",
    category: "Shirts & Pants",
    price: 849,
    originalPrice: 1799,
    discount: 52,
    rating: 4.7,
    reviewCount: 241,
    quantity: 28,
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["#12141d", "#36454f", "#6b4226"],
    colorNames: ["Jet Black", "Charcoal Grey", "Chocolate Brown"],
    gradient: "linear-gradient(135deg, #12141d 0%, #36454f 50%, #4a5568 100%)",
    image: "images/slim_trousers.jpg",
    emoji: "👖",
    isFlashDeal: false,
    isTrending: true,
    description: "Tailored slim-fit formal trousers crafted from a premium poly-viscose blend with a flat-front cut, mid-rise waist, side pockets, and a sharp crease line for a polished professional look.",
    inStock: true
  },
  {
    id: "p15",
    title: "Printed Casual Shirt & Chino Combo",
    brand: "IKON CASUAL",
    category: "Shirts & Pants",
    price: 999,
    originalPrice: 2199,
    discount: 54,
    rating: 4.8,
    reviewCount: 312,
    quantity: 32,
    sizes: ["S", "M", "L", "XL"],
    colors: ["#d4a017", "#228b22", "#8b4513"],
    colorNames: ["Mustard Yellow", "Olive Green", "Rust Brown"],
    gradient: "linear-gradient(135deg, #5c3317 0%, #d4a017 45%, #f0c040 100%)",
    image: "images/casual_combo.jpg",
    emoji: "🧥",
    isFlashDeal: true,
    isTrending: true,
    description: "A curated 2-piece combo featuring a vibrant tropical printed half-sleeve shirt paired with matching slim chino trousers. Made from breathable cotton-linen blend — ideal for weekends and casual hangouts.",
    inStock: true
  },
  {
    id: "p16",
    title: "Argentina 3-Star Premium Club Jersey",
    brand: "IKON SPORTS",
    category: "Club Jersey",
    price: 899,
    originalPrice: 1799,
    discount: 50,
    rating: 4.9,
    reviewCount: 312,
    quantity: 30,
    sizes: ["S", "M", "L", "XL"],
    colors: ["#75aadb", "#ffffff"],
    colorNames: ["Albicelete Blue", "Chalk White"],
    gradient: "linear-gradient(135deg, #75aadb 0%, #ffffff 50%, #75aadb 100%)",
    image: "images/jersey_club_1.jpg",
    emoji: "👕",
    isFlashDeal: true,
    isTrending: true,
    description: "Premium dry-fit breathable polyester fabric jersey featuring Argentina's iconic sky blue and white vertical stripes, gold embroidered 3-stars logo, and moisture-wicking technology.",
    inStock: true
  },
  {
    id: "p17",
    title: "Real Madrid 2026 Home Club Jersey",
    brand: "IKON SPORTS",
    category: "Club Jersey",
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.8,
    reviewCount: 215,
    quantity: 25,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["#ffffff", "#ffd700"],
    colorNames: ["Pure White", "Royal Gold"],
    gradient: "linear-gradient(135deg, #ffffff 0%, #eaeaea 60%, #ffd700 100%)",
    image: "images/jersey_club_2.jpg",
    emoji: "👕",
    isFlashDeal: true,
    isTrending: true,
    description: "Authentic Real Madrid Home Club Jersey crafted with premium double-knit breathable jacquard fabric. Features the signature royal gold lining details and embroidered club crest.",
    inStock: true
  }
];

const CATEGORIES = [
  { id: "all",            label: "All Items",        emoji: "✨" },
  { id: "Club Jersey",    label: "Club Jerseys",      emoji: "⚽" },
  { id: "Streetwear",    label: "Streetwear",        emoji: "🔥" },
  { id: "Western",       label: "Western Wear",      emoji: "👗" },
  { id: "Ethnic",        label: "Ethnic Wear",       emoji: "💎" },
  { id: "Shirts & Pants",label: "Shirts & Pants",    emoji: "👔" },
  { id: "Footwear",      label: "Footwear",          emoji: "👟" },
  { id: "Bags",          label: "Bags & Purses",     emoji: "👜" },
  { id: "Accessories",   label: "Accessories",       emoji: "🕶️" }
];
